### ISSUE TITLE
Just a note, I have experimented firefox without X11 for 8 months

### ISSUE THREAD

**Issue by xhebox** [dylanaraps/wayland-experiment#1]
https://github.com/xhebox/noname-linux/tree/master/ports/firefox, mainly that no-x11.patch. I have no x11 installed at all.

**EDIT**: not really an issue, just a comment, discussion about x11-free configuration is welcome :)

**Comment by dylanaraps** [comment]
Does this mean that no `libX*` libraries are needed at all? ie, nothing X11 related other than libxkbcommon, pixman, xkeyboard-config, etc which are required by Wayland compositors? Also, does the patch allow me to drop X11 from GTK+3, gdk-pixbuf, cairo and libepoxy?

Great work nonetheless. You may find this patch from me handy as well: https://github.com/kisslinux/repo/blob/master/extra/firefox/patches/no-gtk2.patch

**Comment by xhebox** [comment]
> Does this mean that no libX* libraries are needed at all

Yes to this question. No libraries or headers are needed.

> Nothing X11 related other than libxkbcommon, pixman, xkeyboard-config

No, you still need them to get a working wayland desktop. But it is fine to directly compile them without X11, or with some minor patches.

> Also, does the patch allow me to drop X11 from GTK+3, gdk-pixbuf, cairo and libepoxy?

Yes. Like what I said, you can do that. The problem is on firefox. It has lots of hardcoded code relying X11. BTW, I can get firefox working without X11 by my patch, but hardware acceleration may break.

And another sad thing is, wayland does not have any usable IME(just some experimental toys, like mine Chinese wlpinyin).

**Comment by dylanaraps** [comment]
Nice. I'll experiment with your patches over the next week. This is one of the last blockers for an X11 -> Wayland transition for KISS' official repositories. ie, we provide one *or* the other (and not some amalgamation of the two). Thank you once again.

**Comment by xhebox** [comment]
You are welcome. I am glad to refine a better/portable patch. It is kind of dirty.

BTW, there are some strange problems. Sometimes, I can not open firefox(segfault). But a restart of sway will solve the problem. I does not know if it is related to my patch. since I kicked glibc, too.

**Comment by dylanaraps** [comment]
Speaking of issues... I have a rather annoying one where context menus don't work correctly inside Firefox. They will either not appear at all or appear but be un-clickable. Focusing a different workspace and then focusing back seems to force a redraw and prior unresponsive clicks are then acted upon(?).  There's another issue where pressing the hamburger menu button sometimes causes Firefox to segfault. Otherwise, it works very well. VAAPI works fine, things are snappy, no tearing,etc.

(This is using wlroots and sway git master with musl. I'm also **not** using dbus, elogind, seatd, udev, etc.)

**Comment by dylanaraps** [comment]
https://github.com/kisslinux/repo/pull/269 :)

**Comment by xhebox** [comment]
@dylanaraps awesome!
